### ISSUE TITLE
Avatars

### ISSUE THREAD

**Issue by KTS915** [alvarofranz/wp#4]
Nice to see you get started on all this!

I'm not sure how much you would like others getting involved, but I wanted to suggest a slightly different approach to avatars, with the fallback being not an image but an SVG generated on-site of the first letter of the user's display name. I'm attaching a zip (which actually only contains one file) to show how I do avatars at present, via an `mu-plugin`.
[upload-user-avatars.php.zip](https://github.com/alvarofranz/wp/files/8460065/upload-user-avatars.php.zip)

This file also enables the admin to specify where local avatars should be uploaded to.

Obviously, it's your project, so it's up to you what you make of my suggestion!

**Comment by alvarofranz** [comment]
I really like this idea, since it's the modern standard approach for non-defined avatars.

I spent some hours changing the plugin structure. I think a nice solution would be to let the user choose between:

* Default mystery
* Auto generated with first letter
* Custom image

I want to first rewrite the jQuery of this core plugin in vanilla JS and fix potential bugs that there must exists. Then I will take a look at auto generated avatar with first letter.

Thanks!

**Comment by alvarofranz** [comment]
Feature added to the Core Plugin, see #7 

Thanks for the idea and the code.

**Comment by KTS915** [comment]
Glad you found it useful! I have the option to choose folders because it enables me (a) to keep the uploads separate from other files, and (b) to then secure some folders from those who are not logged in for membership sites that I run while leaving other folders to hold uploads that need not be kept secure. But, as I said above, this is your project.
